name: Flutter Build

on:
  push:
    branches:
      - main
      - master
      - dev
      - feature/*

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --target=lib/login.dart --no-tree-shake-icons

      - name: Generate Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to Dropbox
        id: upload_to_dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/app/outputs/flutter-apk/app-release.apk
          dest: /jaberah.apk

      - name: Get Sharable Link from Dropbox
        id: get_sharable_link
        run: |
          response=$(curl -X POST https://api.dropboxapi.com/2/files/get_temporary_link \
            -H "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"path": "/jaberah.apk"}')
          # Extract the link from the JSON response
          link=$(echo $response | jq -r '.link')
          echo "Sharable link: $link"
          echo "::set-output name=link::$link"

      - name: Update Database with Sharable Link
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{secrets.BACKEND_API}}?url=${{ steps.get_sharable_link.outputs.link }}'
          method: 'PUT'
          headers: |
            accept: */*
