name: Flutter Build

on:
  push:
    branches:
      - master
      - main-v2

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install Dependencies
        run: flutter pub get

      - name: Extract App Version
        id: extract_version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d "+" -f 1)
          echo "App version is $version"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release --target=lib/login.dart --no-tree-shake-icons

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/jaberah-${VERSION}.apk

      # Deploy for MASTER
      - name: Update Version in Backend (MASTER)
        if: github.ref == 'refs/heads/master'
        run: |
          response=$(curl -X PUT "${{ secrets.BACKEND_API }}?version=${{ env.VERSION }}" \
            -H "Content-Type: multipart/form-data" \
            -F "apkFile=@build/app/outputs/flutter-apk/jaberah-${VERSION}.apk")
          echo "Response from backend: $response"

      # Deploy for MAIN
      - name: Update Version in Backend (MAIN)
        if: github.ref == 'refs/heads/main-v2'
        run: |
          response=$(curl -X PUT "${{ secrets.BACKEND_API_V2 }}?version=${{ env.VERSION }}" \
            -H "Content-Type: multipart/form-data" \
            -F "apkFile=@build/app/outputs/flutter-apk/jaberah-${VERSION}.apk")
          echo "Response from backend: $response"